stages:
- name: Build and Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: maxatslega/send-email-bot
      pushRemote: true
      registry: pcr.atslega.network
timeout: 60
notification: {}
